setwd("/Users/jamesbyrnes/Desktop/Master")
source("/Users/jamesbyrnes/Desktop/Master/SILAC_Script/SILAC_v2.R")
calRatio3(input = "CD4_Combined_Skyline_Output.csv", para = "parameter_CD4.csv")
write.csv(skypro, "./Script_Output_CD4_2.csv")
log2dist(skypep, style = "box")
HLpro(skypep)
HLpep(skypep)
Volplot(skypro, custom = "", customlab = "normal", r.cutoff = 0.58)
